version: "3.7"
services:
  api:
    image: "ptptsw/product-api:8"
    ports:
      - "19090:9090"
    volumes:
      - ${PWD}/conf.json:/config/config.json
    environment:
      CONFIG_FILE: "/config/config.json"
    depends_on:
      - db
  db:
    image: "ptptsw/product-api-db:v0.0.7"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: "products"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
